### ISSUE TITLE
bitcore-dash production. F.A.O Alex

### ISSUE THREAD

**Issue by Big-Brother** [dashpay/bitcore-dash#4]
Hi

I know this may not be an issue. My head hurts from weeks of googling and trying and trying, and.. trying.

I have successfully installed bitcore-dash on a VPS, but for the life of me I cannot expose it to sub.domain.com to access the block-explorer.

Please.. at present when I run bitcored I get:

[2018-04-15T10:51:23.016Z] info: Using config: /bitcore/.bitcore/bitcore-node-dash.json
[2018-04-15T10:51:23.019Z] info: Using network: livenet
[2018-04-15T10:51:23.020Z] info: Starting bitcoind
[2018-04-15T10:51:23.022Z] info: Using bitcoin config file: /bitcore/.bitcore/data/dash.conf
[2018-04-15T10:51:23.028Z] info: Starting dash process
[2018-04-15T10:51:28.102Z] info: Dash Height: 15688 Percentage: 99.97
[2018-04-15T10:51:28.109Z] info: Dash Daemon Ready
[2018-04-15T10:51:28.110Z] info: Starting web
[2018-04-15T10:51:28.142Z] info: Starting insight-api-dash
[2018-04-15T10:51:28.143Z] info: Starting insight-ui-dash
[2018-04-15T10:51:28.144Z] info: Bitcore Node ready
[2018-04-15T10:51:28.587Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2018-04-15T10:51:28.588Z] info: ZMQ connected to: tcp://127.0.0.1:28332

But, as you can see, it is not running on port:3001 it is using 28332.

What do I need to do to switch this into a live production mode?
what info needs to go into the apache vhost file?

please help.. I have 15 days to get this working, write up and submit, my uni dissertation.

**Comment by Alex-Werner** [comment]
Hi @Big-Brother, 

You are mixing up two things here, what you see in the `ZMQ ....:28332` is the port used by ZMQ and allow to listen about thing happening in dashd, this will be found in data/dash.conf (zmq params). 
You want to access the block-explorer, therefore you want to look at bitcore-node-dash.json, here indeed you should have 3001 as basic port if you didn't change anything. 

The fact that you don't access it from the outside might be due to so many things that I can't tell easily with what you stated here, I would suggest to see if in the VPS you have access to : 

http://localhost:3001/insight/ for the block explorer
or http://localhost:3001/insight-api-dash/status for the API. 

If you can access to it from within, then look at your other configurations.

**Comment by Big-Brother** [comment]
thanks Alex. I installed the server version of ubuntu on the vps, so am I don't have a desktop.

I will have to re-install the vps with a desktop to check. 
I do it now and get back to you right away

**Comment by Alex-Werner** [comment]
You can access it using curl, just do in a terminal : 

`curl http://localhost:3001/insight-api-dash/status`

**Comment by Big-Brother** [comment]
hi Alex. thanks for that.. 

I get a functional status reply that looks good. no errors.

{"info":{"version":120203,"insightversion":"0.6.0","protocolversion":70208,"blocks":853959,"timeoffset":0,"connections":20,"proxy":"","difficulty":111941519.375003,"testnet":false,"relayfee":0.00001,"errors":"","network":"livenet"}}

**Comment by Big-Brother** [comment]
I really appreciate your help. thank you. 
If I can get this working, once my dissertation finished, I can leave the server running almost indefinitely..

**Comment by Alex-Werner** [comment]
Glad everything is good :) 

Right now we are hosting the insight here : https://insight.dashevo.org/insight/

But I won't complain if you decide to let this running, as any node running help securing the network :)

Closing this as everything seems to be fine, good luck with you dissertation ( I would love to have a dissertation on these subject back in my time)
